packages:
  - .
allowBuilds:
  "@embedded-postgres/windows-x64": true
  "@prisma/engines": false
  esbuild: false
  msw: false
  prisma: false
  sharp: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
